### ISSUE TITLE
Fetching plugin fails within incorrect id

### ISSUE THREAD

**Issue by leilahamon** [tgardner/cordova-androidwear#4]
Hi. Thanks for this plugin! I tried installing it, but I received this error:
```
$ cordova plugin add net.trentgardner.cordova.androidwear
Fetching plugin "net.trentgardner.cordova.androidwear" via plugin registry
Installing "net.trentgardner.cordova.androidwear" for android
Fetching plugin "https://github.com/MobileChromeApps/google-play-services" via git clone
Failed to install 'net.trentgardner.cordova.androidwear':Error: Expected fetched plugin to have ID "com.google.playservices@21.0.0" but got "com.google.playservices@21.0.1".
    at checkID (/Users/leila/.npm/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:15)
    at /Users/leila/.npm/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:94:17
    at _fulfilled (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Error: Expected fetched plugin to have ID "com.google.playservices@21.0.0" but got "com.google.playservices@21.0.1".
    at checkID (/Users/leila/.npm/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:15)
    at /Users/leila/.npm/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:94:17
    at _fulfilled (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/leila/.npm/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by HerSaad** [comment]
I have the same Problem  .

**Comment by songokudbz** [comment]
I have the same problem as well.

**Comment by tgardner** [comment]
Hey guys,

I may need to update the publish plugman plugin.

To get you out of trouble can you try:-
`cordova plugin add https://github.com/tgardner/cordova-androidwear.git`

Thanks,

Trent

**Comment by songokudbz** [comment]
It works! 

Thanks

**Comment by HerSaad** [comment]
I tried 
``` cordova plugin add https://github.com/tgardner/cordova-androidwear.git  ```
but it didn't work for me too .
This is the error I received :

``` 
Fetching plugin "https://github.com/tgardner/cordova-androidwear.git" via git clone
Installing "net.trentgardner.cordova.androidwear" for android
Error during processing of action! Attempting to revert...
Failed to install 'net.trentgardner.cordova.androidwear':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at module.exports.framework.install (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at Object.ActionStack.process (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
    at handleInstall (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
    at _fulfilled (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at module.exports.framework.install (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at Object.ActionStack.process (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
    at handleInstall (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
    at _fulfilled (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
``` 
Thanks

**Comment by tgardner** [comment]
Hi HerSaad,

You need to install Google Play Services using your android SDK manager.

Then try again.


Thanks

**Comment by HerSaad** [comment]
Hi @tgardner ,

Google Play Services is already installed .

![googleplayservices](https://cloud.githubusercontent.com/assets/13237469/8593833/8594d086-263b-11e5-9d65-88000d706680.jpg)

And I have made some Examples that send a String  from my phone to my wear and they are working well !

Thanks .

**Comment by tgardner** [comment]
Hi @HerSaad,

Sorry, I'm not following you. You've got it working, but you can't install the plugin? The former contradicts the later?

What is it that you're actually having issues in achieving?

Thanks

**Comment by HerSaad** [comment]
Hi @tgardner ,
I have not got it working so far .
I tried to say that I have made some android native Examples that are working well witch means that the google play services is already installed .
Thank you .

**Comment by tgardner** [comment]
Hi @HerSaad,

I've updated plugman, do you have any better luck with `cordova plugin add net.trentgardner.cordova.androidwear`?

**Comment by HerSaad** [comment]
Hi @tgardner ,
 Thank you for updating plugman but I still have the same Problem : Arguments to path.resolve must be strings .

```
Failed to install 'net.trentgardner.cordova.androidwear':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at module.exports.framework.install (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at Object.ActionStack.process (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
    at handleInstall (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
    at _fulfilled (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at module.exports.framework.install (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at Object.ActionStack.process (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
    at handleInstall (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
    at _fulfilled (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Saad\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)

```

**Comment by tgardner** [comment]
Hi @HerSaad,

This seems to be a separate issue. Can you please try updating cordova, and if the problem persists, please open another issue.

Thanks,

Trent
